export const mapsMappear = [
  { nameMaps: 'Afghanistan', nameApi: 'Afghanistan' },
  { nameMaps: 'Angola', nameApi: 'Angola' },
  { nameMaps: 'Albania', nameApi: 'Albania' },
  { nameMaps: 'United Arab Emirates', nameApi: 'United Arab Emirates' },
  { nameMaps: 'Argentina', nameApi: 'Argentina' },
  { nameMaps: 'Armenia', nameApi: 'Armenia' },
  { nameMaps: 'Antarctica', nameApi: 'Antarctica' },
  { nameMaps: 'Fr. S. Antarctic Lands', nameApi: 'Fr. S. Antarctic Lands' },
  { nameMaps: 'Australia', nameApi: 'Australia' },
  { nameMaps: 'Austria', nameApi: 'Austria' },
  { nameMaps: 'Azerbaijan', nameApi: 'Azerbaijan' },
  { nameMaps: 'Burundi', nameApi: 'Burundi' },
  { nameMaps: 'Belgium', nameApi: 'Belgium' },
  { nameMaps: 'Benin', nameApi: 'Benin' },
  { nameMaps: 'Burkina Faso', nameApi: 'Faso' },
  { nameMaps: 'Bangladesh', nameApi: 'Bangladesh' },
  { nameMaps: 'Bulgaria', nameApi: 'Bulgaria' },
  { nameMaps: 'Bahamas', nameApi: 'Bahamas' },
  { nameMaps: 'Bosnia and Herz.', nameApi: 'Bosnia and Herzegovina' },
  { nameMaps: 'Belarus', nameApi: 'Belarus' },
  { nameMaps: 'Belize', nameApi: 'Belize' },
  { nameMaps: 'Bolivia', nameApi: 'Bolivia' },
  { nameMaps: 'Brazil', nameApi: 'Brazil' },
  { nameMaps: 'Brunei', nameApi: 'Brunei' },
  { nameMaps: 'Bhutan', nameApi: 'Bhutan' },
  { nameMaps: 'Botswana', nameApi: 'Botswana' },
  { nameMaps: 'Central African Rep.', nameApi: 'Central African Rep.' },
  { nameMaps: 'Canada', nameApi: 'Canada' },
  { nameMaps: 'Switzerland', nameApi: 'Switzerland' },
  { nameMaps: 'Chile', nameApi: 'Chile' },
  { nameMaps: 'China', nameApi: 'China' },
  { nameMaps: "Côte d'Ivoire", nameApi: "Côte d'Ivoir" },
  { nameMaps: 'Cameroon', nameApi: 'Cameroon' },
  { nameMaps: 'Dem. Rep. Congo', nameApi: 'Congo' },
  { nameMaps: 'Congo', nameApi: 'Congo' },
  { nameMaps: 'Colombia', nameApi: 'Colombia' },
  { nameMaps: 'Costa Rica', nameApi: 'Rica' },
  { nameMaps: 'Cuba', nameApi: 'Cuba' },
  { nameMaps: 'N. Cyprus', nameApi: 'N. Cyprus' },
  { nameMaps: 'Cyprus', nameApi: 'Cyprus' },
  { nameMaps: 'Czechia', nameApi: 'Czechia' },
  { nameMaps: 'Germany', nameApi: 'Germany' },
  { nameMaps: 'Djibouti', nameApi: 'Djibouti' },
  { nameMaps: 'Denmark', nameApi: 'Denmark' },
  { nameMaps: 'Dominican Rep.', nameApi: 'Dominican Republic' },
  { nameMaps: 'Algeria', nameApi: 'Algeria' },
  { nameMaps: 'Ecuador', nameApi: 'Ecuador' },
  { nameMaps: 'Egypt', nameApi: 'Egypt' },
  { nameMaps: 'Eritrea', nameApi: 'Eritrea' },
  { nameMaps: 'Spain', nameApi: 'Spain' },
  { nameMaps: 'Estonia', nameApi: 'Estonia' },
  { nameMaps: 'Ethiopia', nameApi: 'Ethiopia' },
  { nameMaps: 'Finland', nameApi: 'Finland' },
  { nameMaps: 'Fiji', nameApi: 'Fiji' },
  { nameMaps: 'Falkland Is.', nameApi: 'Falkland Is.' },
  { nameMaps: 'France', nameApi: 'France' },
  { nameMaps: 'Gabon', nameApi: 'Gabon' },
  { nameMaps: 'United Kingdom', nameApi: 'United Kingdom' },
  { nameMaps: 'Georgia', nameApi: 'Georgia' },
  { nameMaps: 'Ghana', nameApi: 'Ghana' },
  { nameMaps: 'Guinea', nameApi: 'Guinea' },
  { nameMaps: 'Gambia', nameApi: 'Gambia' },
  { nameMaps: 'Guinea-Bissau', nameApi: 'Guinea-Bissau' },
  { nameMaps: 'Eq. Guinea', nameApi: 'Guinea' },
  { nameMaps: 'Greece', nameApi: 'Greece' },
  { nameMaps: 'Greenland', nameApi: 'Greenland' },
  { nameMaps: 'Guatemala', nameApi: 'Guatemala' },
  { nameMaps: 'Guyana', nameApi: 'Guyana' },
  { nameMaps: 'Honduras', nameApi: 'Honduras' },
  { nameMaps: 'Croatia', nameApi: 'Croatia' },
  { nameMaps: 'Haiti', nameApi: 'Haiti' },
  { nameMaps: 'Hungary', nameApi: 'Hungary' },
  { nameMaps: 'Indonesia', nameApi: 'Indonesia' },
  { nameMaps: 'India', nameApi: 'India' },
  { nameMaps: 'Ireland', nameApi: 'Ireland' },
  { nameMaps: 'Iran', nameApi: 'Iran' },
  { nameMaps: 'Iraq', nameApi: 'Iraq' },
  { nameMaps: 'Iceland', nameApi: 'Iceland' },
  { nameMaps: 'Israel', nameApi: 'Israel' },
  { nameMaps: 'Italy', nameApi: 'Italy' },
  { nameMaps: 'Jamaica', nameApi: 'Jamaica' },
  { nameMaps: 'Jordan', nameApi: 'Jordan' },
  { nameMaps: 'Japan', nameApi: 'Japan' },
  { nameMaps: 'Kazakhstan', nameApi: 'Kazakhstan' },
  { nameMaps: 'Kenya', nameApi: 'Kenya' },
  { nameMaps: 'Kyrgyzstan', nameApi: 'Kyrgyzstan' },
  { nameMaps: 'Cambodia', nameApi: 'Cambodia' },
  { nameMaps: 'South Korea', nameApi: 'South Korea' },
  { nameMaps: 'Kosovo', nameApi: 'Kosovo' },
  { nameMaps: 'Kuwait', nameApi: 'Kuwait' },
  { nameMaps: 'Laos', nameApi: 'Laos' },
  { nameMaps: 'Lebanon', nameApi: 'Lebanon' },
  { nameMaps: 'Liberia', nameApi: 'Liberia' },
  { nameMaps: 'Libya', nameApi: 'Libya' },
  { nameMaps: 'Sri Lanka', nameApi: 'Sri Lanka' },
  { nameMaps: 'Lesotho', nameApi: 'Lesotho' },
  { nameMaps: 'Lithuania', nameApi: 'Lithuania' },
  { nameMaps: 'Luxembourg', nameApi: 'Luxembourg' },
  { nameMaps: 'Latvia', nameApi: 'Latvia' },
  { nameMaps: 'Morocco', nameApi: 'Morocco' },
  { nameMaps: 'Moldova', nameApi: 'Moldova' },
  { nameMaps: 'Madagascar', nameApi: 'Madagascar' },
  { nameMaps: 'Mexico', nameApi: 'Mexico' },
  { nameMaps: 'Macedonia', nameApi: 'Macedonia' },
  { nameMaps: 'Mali', nameApi: 'Mali' },
  { nameMaps: 'Myanmar', nameApi: 'Myanmar' },
  { nameMaps: 'Montenegro', nameApi: 'Montenegro' },
  { nameMaps: 'Mongolia', nameApi: 'Mongolia' },
  { nameMaps: 'Mozambique', nameApi: 'Mozambique' },
  { nameMaps: 'Mauritania', nameApi: 'Mauritania' },
  { nameMaps: 'Malawi', nameApi: 'Malawi' },
  { nameMaps: 'Malaysia', nameApi: 'Malaysia' },
  { nameMaps: 'Namibia', nameApi: 'Namibia' },
  { nameMaps: 'New Caledonia', nameApi: 'Caledonia' },
  { nameMaps: 'Niger', nameApi: 'Niger' },
  { nameMaps: 'Nigeria', nameApi: 'Nigeria' },
  { nameMaps: 'Nicaragua', nameApi: 'Nicaragua' },
  { nameMaps: 'Netherlands', nameApi: 'Netherlands' },
  { nameMaps: 'Norway', nameApi: 'Norway' },
  { nameMaps: 'Nepal', nameApi: 'Nepal' },
  { nameMaps: 'New Zealand', nameApi: 'New Zealand' },
  { nameMaps: 'Oman', nameApi: 'Oman' },
  { nameMaps: 'Pakistan', nameApi: 'Pakistan' },
  { nameMaps: 'Panama', nameApi: 'Panama' },
  { nameMaps: 'Peru', nameApi: 'Peru' },
  { nameMaps: 'Philippines', nameApi: 'Philippines' },
  { nameMaps: 'Papua New Guinea', nameApi: 'Papua New Guinea' },
  { nameMaps: 'Poland', nameApi: 'Poland' },
  { nameMaps: 'Puerto Rico', nameApi: 'Puerto Rico' },
  { nameMaps: 'North Korea', nameApi: 'North Korea' },
  { nameMaps: 'Portugal', nameApi: 'Portugal' },
  { nameMaps: 'Paraguay', nameApi: 'Paraguay' },
  { nameMaps: 'Palestine', nameApi: 'Palestine' },
  { nameMaps: 'Qatar', nameApi: 'Qatar' },
  { nameMaps: 'Romania', nameApi: 'Romania' },
  { nameMaps: 'Russia', nameApi: 'Russia' },
  { nameMaps: 'Rwanda', nameApi: 'Rwanda' },
  { nameMaps: 'W. Sahara', nameApi: 'W. Sahara' },
  { nameMaps: 'Saudi Arabia', nameApi: 'Saudi Arabia' },
  { nameMaps: 'Sudan', nameApi: 'Sudan' },
  { nameMaps: 'S. Sudan', nameApi: 'S. Sudan' },
  { nameMaps: 'Senegal', nameApi: 'Senegal' },
  { nameMaps: 'Solomon Is.', nameApi: 'Solomon Is' },
  { nameMaps: 'Sierra Leone', nameApi: 'Sierra Leone' },
  { nameMaps: 'El Salvador', nameApi: 'El Salvador' },
  { nameMaps: 'Somaliland', nameApi: 'Somaliland' },
  { nameMaps: 'Somalia', nameApi: 'Somalia' },
  { nameMaps: 'Serbia', nameApi: 'Serbia' },
  { nameMaps: 'Suriname', nameApi: 'Suriname' },
  { nameMaps: 'Slovakia', nameApi: 'Slovakia' },
  { nameMaps: 'Slovenia', nameApi: 'Slovenia' },
  { nameMaps: 'Sweden', nameApi: 'Sweden' },
  { nameMaps: 'Swaziland', nameApi: 'Swaziland' },
  { nameMaps: 'Syria', nameApi: 'Syria' },
  { nameMaps: 'Chad', nameApi: 'Chad' },
  { nameMaps: 'Togo', nameApi: 'Togo' },
  { nameMaps: 'Thailand', nameApi: 'Thailand' },
  { nameMaps: 'Tajikistan', nameApi: 'Tajikistan' },
  { nameMaps: 'Turkmenistan', nameApi: 'Turkmenistan' },
  { nameMaps: 'Timor-Leste', nameApi: 'Leste' },
  { nameMaps: 'Trinidad and Tobago', nameApi: 'Trinidad and Tobago' },
  { nameMaps: 'Tunisia', nameApi: 'Tunisia' },
  { nameMaps: 'Turkey', nameApi: 'Turkey' },
  { nameMaps: 'Taiwan', nameApi: 'Taiwan' },
  { nameMaps: 'Tanzania', nameApi: 'Tanzania' },
  { nameMaps: 'Uganda', nameApi: 'Uganda' },
  { nameMaps: 'Ukraine', nameApi: 'Ukraine' },
  { nameMaps: 'Uruguay', nameApi: 'Uruguay' },
  { nameMaps: 'United States of America', nameApi: 'United States' },
  { nameMaps: 'Uzbekistan', nameApi: 'Uzbekistan' },
  { nameMaps: 'Venezuela', nameApi: 'Venezuela' },
  { nameMaps: 'Vietnam', nameApi: 'Vietnam' },
  { nameMaps: 'Vanuatu', nameApi: 'Vanuatu' },
  { nameMaps: 'Yemen', nameApi: 'Yemen' },
  { nameMaps: 'South Africa', nameApi: 'South Africa' },
  { nameMaps: 'Zambia', nameApi: 'Zambia' },
  { nameMaps: 'Zimbabwe', nameApi: 'Zimbabwe' },
];
